export const TOKEN_ERROR_STATUS = {
  NO_TOKEN: "TOKEN_0001",
  INVALID_TOKEN: "TOKEN_0002",
  AUTH_FAILED: "TOKEN_0003",
  INVALID_REFRESH_TOKEN: "TOKEN_0004",
  UNAUTHORIZED: "TOKEN_0005",
  EXPIRED_REFRESH_TOKEN: "TOKEN_0006",
  OUTDATED_REFRESH_TOKEN: "TOKEN_0007",
} as const;
